language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install -U coverage
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - coverage run -m pytest
  - coverage report -m